apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- services.yaml
- volume.yaml

configMapGenerator:
- name: database-config
  literals:
    - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD="0"
    - MARIADB_DATABASE="naad_connector"

secretGenerator:
- name: database-secrets
  literals:
    - MARIADB_ROOT_PASSWORD="rootpassword"
  type: Opaque

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/part-of: naad-connector
