apiVersion: batch/v1
kind: Job
metadata:
  name: run-database-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    app.kubernetes.io/name: database-migrations
spec:
  template:
    spec:
      containers:
        - name: migration
          image: your-app-image:latest
          command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction", "--allow-no-migration"]
          envFrom:
            - secretRef:
                name: database-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
