apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the MariaDB database to the NAAD Connector pods.
  name: naad-mariadb
  namespace: default
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  sessionAffinity: None
  type: ClusterIP
