apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- phpmyadmin

# Overrides the namespace
namespace: default

labels:
- includeSelectors: true
  pairs:
    app: naad-app
    env: local

images:
- name: bcgovgdx/naad-app
  newTag: latest

patches:
- path: pvc-patch.yaml
  target:
    name: naad-logs
- path: image-pull-policy-patch.yaml
  target:
    name: naad-socket
- path: image-pull-policy-patch.yaml
  target:
    name: database-migration
- path: cron-image-pull-policy-patch.yaml
  target:
    name: alert-cleanup