services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - naad-database:/var/lib/mysql
    networks:
      - naad_deploy
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin -u root -p${MARIADB_ROOT_PASSWORD} ping -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always

  database-migrate:
    image: bcgovgdx/naad-app
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_SERVICE_HOST: mariadb
      MARIADB_SERVICE_PORT: 3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    depends_on:
      mariadb:
        condition: service_healthy
    entrypoint: ["vendor/bin/doctrine-migrations", "-vvv", "-n", "migrate"]
    networks:
      - naad_deploy

  naad-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bcgovgdx/naad-app
    environment:
      DESTINATION_URL: ${DESTINATION_URL:-https://0.0.0.0/wp-json/naad/v1/alert}
      DESTINATION_USER: ${DESTINATION_USER}
      DESTINATION_PASSWORD: ${DESTINATION_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_SERVICE_HOST: mariadb
      MARIADB_SERVICE_PORT: 3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      NAAD_NAME: ${NAAD_NAME}
      NAAD_URL: ${NAAD_URL}
      NAAD_REPO_URL: ${NAAD_REPO_URL}
      NAAD_PORT: ${NAAD_PORT}
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
    depends_on:
      database-migrate:
        condition: service_completed_successfully
    ports:
      - "${NAAD_PORT:-8080}:80"
    networks:
      - naad_deploy
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    depends_on:
      naad-app:
        condition: service_started
    environment:
      PMA_HOST: ${MARIADB_SERVICE_HOST}
      PMA_PORT: ${MARIADB_SERVICE_HOST}
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8082}:80"
    networks:
      - naad_deploy

networks:
  naad_deploy:

volumes:
  naad-database:
