services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306" # set to 3307 to avoid conflict with our wordpress environment's mariadb container
    volumes:
      - naad-database:/var/lib/mysql
    networks:
      - naad_deploy
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin -u root -p${MARIADB_ROOT_PASSWORD} ping -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # wait for mariadb to start up
  database-migrate:
    image: bcgovgdx/naad-app
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} # Loaded from .env
      MARIADB_SERVICE_HOST: mariadb
      MARIADB_SERVICE_PORT: 3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    depends_on:
      mariadb:
        condition: service_healthy
    entrypoint: ["vendor/bin/doctrine-migrations", "-vvv", "-n", "migrate"]
    networks:
      - naad_deploy

  # wait for database migration to complete
  naad-app:
    image: bcgovgdx/naad-app
    environment:
      DESTINATION_URL: ${DESTINATION_URL:-https://0.0.0.0/wp-json/naad/v1/alert}
      DESTINATION_USER: ${DESTINATION_USER} # Loaded from .env
      DESTINATION_PASSWORD: ${DESTINATION_PASSWORD} # Loaded from .env
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} # Loaded from .env
      MARIADB_SERVICE_HOST: mariadb
      MARIADB_SERVICE_PORT: 3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      NAAD_NAME: NAAD-1
      NAAD_URL: streaming1.naad-adna.pelmorex.com
      NAAD_REPO_URL: capcp1.naad-adna.pelmorex.com
    depends_on:
      database-migrate:
        condition: service_completed_successfully
    ports:
      - "${NAAD_PORT:-8080}:80"
    networks:
      - naad_deploy
    restart: always

  # Lastly, wait for the naad-app to start up
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      naad-app:
        condition: service_started
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - naad_deploy
    ports:
      # default port for phpMyAdmin set to 8082 so there is no conflict with our wordpress container's myphpAdmin
      - "${PHPMYADMIN_PORT:-8082}:80"

networks:
  naad_deploy:

volumes:
  naad-database:
