apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app.kubernetes.io/version:	11.5.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: phpmyadmin-config
          env:
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: MARIADB_ROOT_PASSWORD