kind: Deployment
apiVersion: apps/v1
metadata:
  name: naad-socket
  labels:
    app.kubernetes.io/name: naad-socket
    app.kubernetes.io/instance: naad-1
    app.openshift.io/runtime: php
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: naad-app
          image: bcgovgdx/naad-app
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: naad-config
          - secretRef:
              name: naad-secrets
          - secretRef:
              name: database-secrets
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
              - /var/www/html/liveness.sh
            initialDelaySeconds: 60
            periodSeconds: 60