kind: Deployment
apiVersion: apps/v1
metadata:
  name: naad-socket-2
  labels:
    app.kubernetes.io/name: naad-socket-2
    app.kubernetes.io/instance: naad-2
    app.openshift.io/runtime: php
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: naad-logs
      containers:
        - name: naad-app
          image: bcgovgdx/naad-app
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: naad2-config
          - configMapRef:
              name: naad-shared-config
          - configMapRef:
              name: database-config
          - secretRef:
              name: naad-secrets
          - secretRef:
              name: database-secrets
          volumeMounts:
          - name: logs-volume
            mountPath: /var/log/app/
            subPath: naad-2
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
              - /app/liveness.sh
            initialDelaySeconds: 60
            periodSeconds: 120
            failureThreshold: 3
      initContainers:
        - name: wait-for-db
          image: busybox
          env:
            - name: MARIADB_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MARIADB_SERVICE_HOST
            - name: MARIADB_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MARIADB_SERVICE_PORT
          command: ['sh', '-c', 'until nc -z $MARIADB_SERVICE_HOST $MARIADB_SERVICE_PORT; do echo waiting for database $MARIADB_SERVICE_HOST; sleep 2; done']