apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- deployment2.yaml
- job.yaml
- alert-cleanup.yaml
- volume.yaml

configMapGenerator:
- name: naad1-config
  literals:
    - NAAD_NAME=NAAD-1
    - NAAD_URL=streaming1.naad-adna.pelmorex.com
    - NAAD_REPO_URL=capcp1.naad-adna.pelmorex.com
    - LOG_PATH=/var/log/app/naad-1/app.log
- name: naad2-config
  literals:
    - NAAD_NAME=NAAD-2
    - NAAD_URL=streaming2.naad-adna.pelmorex.com
    - NAAD_REPO_URL=capcp2.naad-adna.pelmorex.com
    - LOG_PATH=/var/log/app/naad-2/app.log
- name: cron-alert-cleanup-config
  literals:
    - NAAD_NAME=NAAD-Alert-Cleanup
    - NAAD_URL=streaming1.naad-adna.pelmorex.com
    - NAAD_REPO_URL=capcp1.naad-adna.pelmorex.com
    - LOG_PATH=/var/log/app/cron/alert-cleanup.log
- name: naad-shared-config
  literals:
    - DESTINATION_URL="http://local:38080/embc/wp-json/naad/v1/alert"
    - DESTINATION_USER=naadbot
    - LOG_LEVEL=info
    - LOG_RETENTION_DAYS=365
    - ALERTS_TO_KEEP=100
    - LOG_PATH=/tmp/logs/

secretGenerator:
- name: naad-secrets
  literals:
    - DESTINATION_PASSWORD='AAAA AAAA AAAA AAAA'
  type: Opaque

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: socket
    app.kubernetes.io/part-of: naad-connector
