apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- job.yaml

# Updates the labels for all containers.
commonLabels:
  app.kubernetes.io/component: socket
  app.kubernetes.io/part-of: naad-connector
configMapGenerator:
  - name: naad-config
    literals:
    - NAAD_NAME=NAAD-1
    - NAAD_URL=streaming1.naad-adna.pelmorex.com
    - DESTINATION_URL=https://localhost/wp-json/naad/v1/alert
    - DESTINATION_USER=naadbot

secretGenerator:
  - name: naad-secrets
    type: Opaque
    literals:
    - DESTINATION_PASSWORD='AAAA AAAA AAAA AAAA'