apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-cleanup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: logs-volume
              persistentVolumeClaim:
                claimName: naad-logs
          containers:
          - name: alert-cleanup
            image: bcgovgdx/naad-app
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: cron-alert-cleanup-config
            - configMapRef:
                name: naad-shared-config
            - configMapRef:
                name: database-config
            # - secretRef:
            #     name: naad-secrets
            # - secretRef:
            #     name: database-secrets
            command: ["/bin/sh", "-c", "php src/alert-cleanup.php"]