apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-cleanup
spec:
  schedule: "*/1 * * * *"  # Runs every 1 minutes.
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-token: 'true'
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/auth-path: auth/k8s-silver
            vault.hashicorp.com/namespace: platform-services
            vault.hashicorp.com/secret-volume-path: /vault/secrets
            vault.hashicorp.com/role: bdf349-nonprod
            vault.hashicorp.com/agent-inject-secret-naad: bfd349-nonprod/dev
            vault.hashicorp.com/agent-inject-template-naad: |
              {{- with secret "bdf349-nonprod/dev" -}}
              export DESTINATION_PASSWORD="{{ .Data.data.DESTINATION_PASSWORD }}"
              export MARIADB_ROOT_PASSWORD="{{ .Data.data.MARIADB_ROOT_PASSWORD }}"
              export MARIADB_SERVICE_HOST="{{ .Data.data.MARIADB_SERVICE_HOST }}"
              export MARIADB_SERVICE_PORT="{{ .Data.data.MARIADB_SERVICE_PORT }}"
              {{- end }}
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: logs-volume
              persistentVolumeClaim:
                claimName: naad-logs
          containers:
          - name: alert-cleanup
            image: bcgovgdx/naad-app
            imagePullPolicy: IfNotPresent
            command:
              - 'sh'
              - '-c'
              - |
                echo "Waiting for Vault secrets to be injected..."
                while [ ! -f /vault/secrets/naad ]; do
                  echo "Waiting for /vault/secrets/naad to be available..."
                  sleep 2
                done
                echo "Vault secrets are available."
                . /vault/secrets/naad
                echo "Waiting for MariaDB to be ready..."
                until nc -z $MARIADB_SERVICE_HOST $MARIADB_SERVICE_PORT; do
                  echo "Waiting for database $MARIADB_SERVICE_HOST:$MARIADB_SERVICE_PORT..."
                  sleep 2
                done
                echo "$MARIADB_SERVICE_HOST:$MARIADB_SERVICE_PORT is up and running."
                php src/alert-cleanup.php
          serviceAccountName: bdf349-vault
          serviceAccount: bdf349-vault
  backoffLimit: 100