apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bdf349-dev

images:
- name: bcgovgdx/naad-app
  newName: image-registry.openshift-image-registry.svc:5000/bdf349-tools/naad-app
  newTag: latest

configMapGenerator:
- behavior: merge
  name: naad-shared-config
  literals:
  - DESTINATION_URL=https://test.vanity.blog.gov.bc.ca/embc/wp-json/naad/v1/alert
  - DESTINATION_USER=admin

resources:
- ../openshift

labels:
- includeSelectors: true
  pairs:
    env: dev

patches:
- path: migrate-job.yaml
- path: naad1.yaml
- path: naad2.yaml
- path: database.yaml
- path: alerts-cronjob.yaml