apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bdf349-dev

images:
- name: bcgovgdx/naad-app
  newName: image-registry.openshift-image-registry.svc:5000/bdf349-tools/naad-app
  newTag: latest

configMapGenerator:
- behavior: merge
  name: naad-shared-config
  literals:
  - DESTINATION_URL=https://test.vanity.blog.gov.bc.ca/embc/wp-json/naad/v1/alert
  - DESTINATION_USER=admin
# - name: mariadb-entrypoint
#   files:
#   - entrypoint.sh
#   options:
#     disableNameSuffixHash: true

secretGenerator:
- behavior: merge
  name: naad-secrets
  literals:
  - DESTINATION_PASSWORD='IwO0 XTqC isv2 j9ei GINk 2Z1g'
  type: Opaque
- behavior: merge
  name: database-secrets
  literals:
  - MARIADB_ROOT_PASSWORD="RgO4.%541gjWqoEHDR$}#pfM?VZjcv4wsl3g;if-uwKM]OC;)@"
  - MARIADB_SERVICE_HOST="mariadb"
  - MARIADB_SERVICE_PORT=3306
  type: Opaque

resources:
- ../openshift

labels:
- includeSelectors: true
  pairs:
    env: dev

patches:
- path: migrate-job.yaml
- path: naad1.yaml
- path: naad2.yaml
- path: database-with-inline-script.yaml
#- path: database-using-generated-configmap-script.yaml
#- path: remove-database-secrets.yaml  # Add this line to apply the patch
#- path: database-with-init-container.yaml
#- path: database.yaml
#- path: working-basic-patch.yaml
#- path: working-vault-patch.yaml