apiVersion: apps/v1
kind: Deployment
metadata:
  name: naad-socket-2
  annotations:
    image.openshift.io/triggers: '[{ "from": { "kind": "ImageStreamTag", "name": "naad-app:latest",
      "namespace": "bdf349-tools" }, "fieldPath": "spec.template.spec.containers[?(@.name==\"naad-app\")].image"
      }]'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/auth-path: auth/k8s-silver
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/secret-volume-path: /vault/secrets
        vault.hashicorp.com/role: bdf349-nonprod
        vault.hashicorp.com/agent-inject-secret-naad: bfd349-nonprod/dev
        vault.hashicorp.com/agent-inject-template-naad: |
          {{- with secret "bdf349-nonprod/dev" -}}
          export VAULT_DESTINATION_PASSWORD="{{ .Data.data.DESTINATION_PASSWORD }}"
          export MARIADB_ROOT_PASSWORD="{{ .Data.data.MARIADB_ROOT_PASSWORD }}"
          export MARIADB_SERVICE_HOST="{{ .Data.data.MARIADB_SERVICE_HOST }}"
          export MARIADB_SERVICE_PORT="{{ .Data.data.MARIADB_SERVICE_PORT }}"
          {{- end }}
    spec:
      containers:
      - name: naad-app
        image: bcgovgdx/naad-app
        imagePullPolicy: Always
        command:
        - /app/entrypoint.sh
      serviceAccountName: bdf349-vault
      serviceAccount: bdf349-vault
