kind: Deployment
apiVersion: apps/v1
metadata:
  name: naad-app-deployment
  labels:
    app.kubernetes.io/name: naad-app
    app.kubernetes.io/instance: naad-1
    app.kubernetes.io/part-of: naad-connector
    app.openshift.io/runtime: php
    app.kubernetes.io/component: socket
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: naad-app
          image: bcgovgdx/naad-app
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: config
          - secretRef:
              name: secrets
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi