kind: Deployment
apiVersion: apps/v1
metadata:
  name: naad-app-deployment
  labels:
    app.kubernetes.io/name: naad-app
    app.kubernetes.io/instance: naad-1
    app.kubernetes.io/part-of: naad-connector
    app.openshift.io/runtime: php
    app.kubernetes.io/component: socket
    
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: naad-app
          image: image-registry.openshift-image-registry.svc:5000/e9b785-tools/naad-app:latest
          imagePullPolicy: Always
          env:
            - name: NAAD_NAME
              value: NAAD-1
            - name: NAAD_URL
              value: "streaming1.naad-adna.pelmorex.com"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 2Gi