apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    app.kubernetes.io/name: database-migration
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
        - name: naad-database-migration
          image: bcgovgdx/naad-app:1.0.0
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: database-config
          - secretRef:
              name: root-database-secrets
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "1Gi"
              cpu: 500m
              memory: 1Gi
          command: ["/bin/bash", "/app/run-migrations.sh"]
  backoffLimit: 100