apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  labels:
    app.kubernetes.io/name: database-volume
    app.kubernetes.io/component: database
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  