apiVersion: batch/v1
kind: Job
metadata:
  name: database-create-user
  labels:
      app.kubernetes.io/name: database-create-user
      app.kubernetes.io/instance: naad
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: naad-connector
      app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/name: database-create-user
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 100
  template:
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
      - name: create-user
        image: mariadb:12.1.2
        command: ['sh', '-c']
        args:
          - |
            # Create the user and grant it privileges.
            mariadb $MARIADB_DATABASE -h "$MARIADB_SERVICE_HOST" -P "$MARIADB_SERVICE_PORT" -u root -p"$MARIADB_ROOT_PASSWORD" -e "
            CREATE OR REPLACE USER '$MARIADB_SERVICE_USER'@'%' IDENTIFIED BY '$MARIADB_SERVICE_PASSWORD';
            GRANT CREATE, ALTER, SELECT, INSERT, UPDATE, DELETE ON $MARIADB_DATABASE.* TO '$MARIADB_SERVICE_USER'@'%';"
        envFrom:
          - configMapRef:
              name: database-config
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: root-database-secrets
                key: MARIADB_ROOT_PASSWORD
          - name: MARIADB_SERVICE_USER
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: MARIADB_SERVICE_USER
          - name: MARIADB_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: MARIADB_SERVICE_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 10Mi
          limits:
            cpu: 100m
            memory: 128Mi

