apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app
- database


# Overrides the namespace
namespace: default

labels:
- includeSelectors: true
  pairs:
    app: naad-app
    env: default
