apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml

# Updates the labels for all containers.
commonLabels:
  app: naad-app
  env: default
configMapGenerator:
  - name: config
    literals:
    - NAAD_NAME=NAAD-1
    - NAAD_URL=streaming1.naad-adna.pelmorex.com
    - DESTINATION_URL=https://localhost/wp-json/naad/v1/alert
    - DESTINATION_USER=naadbot

secretGenerator:
  - name: secrets
    type: Opaque
    literals:
    - DESTINATION_PASSWORD='AAAA AAAA AAAA AAAA'