apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naad-logs
  labels:
    app.kubernetes.io/name: naad-logs
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
