apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  automountServiceAccountToken: false
  containers:
    - name: sidecar
      image: alpine:3
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: logs-volume
          mountPath: /var/log/
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
          ephemeral-storage: 16Mi
        limits:
          cpu: 50m
          memory: 64Mi
          ephemeral-storage: 32Mi

  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: naad-logs
