apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-build
spec:
  workspaces:
    - name: results-ws
  results:
    - description: Output of the start-build command
      name: build-output
      type: string
    - description: Status of the build ("Build Succeeded" or "Build Failed")
      name: exit-status
      type: string
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: start-build
      resources: {}
      script: |
        #!/bin/sh
        output=$(oc start-build naad-app --wait)
        exit_code=$?
        echo "$output" > $(results.build-output.path)
        if [ "$exit_code" -eq 0 ]; then
          oc tag naad-app:latest naad-app:dev
          echo -n "Build Succeeded" > $(results.exit-status.path)
        else
          echo -n "Build Failed" > $(results.exit-status.path)
        fi
        exit 0  # Continue the pipeline even if the task fails