apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/auth-path: auth/k8s-silver
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/secret-volume-path: /vault/secrets
        vault.hashicorp.com/role: bdf349-nonprod
        vault.hashicorp.com/agent-inject-secret-naad: bfd349-nonprod/dev
        vault.hashicorp.com/agent-inject-template-naad: |
          {{- with secret "bdf349-nonprod/dev" -}}
          # at one point i had this configured with the values from /vault/secrets/naad
          postgres://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/appdb?sslmode=disable
          {{- end }}
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.5.2
      serviceAccountName: bdf349-vault
      serviceAccount: bdf349-vault