apiVersion: apps/v1
kind: Deployment
metadata:
  name: naad-socket-1
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
      - name: naad-app
        image: bcgovgdx/naad-app