services:
  app:
    env_file:
      - path: ./devcontainer.env
        required: true
      - path: ./override.env
        required: false
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ../logs:/logs
      # Used for testing secrets from file
      - ../secrets:/vault/secrets

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    external_links:
      - mariadb
    extra_hosts:
      - "local:host-gateway"

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  mariadb:
    image: mariadb:11
    env_file:
      - path: ./devcontainer.env
        required: true
      - path: ./override.env
        required: false
    volumes:
      - naad-database:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - path: ./devcontainer.env
        required: true
      - path: ./override.env
        required: false
    ports:
      - "${PHPMYADMIN_PORT:-8082}:80"

volumes:
  naad-database:
