apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    app.kubernetes.io/name: database-migration
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
        - name: naad-database-migration
          image: bcgovgdx/naad-app
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: database-config
          - secretRef:
              name: database-secrets
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          command: ['vendor/bin/doctrine-migrations', 'migrate', '--no-interaction', '--allow-no-migration']
      initContainers:
        - name: wait-for-db
          image: busybox
          envFrom:
          - configMapRef:
              name: database-config
          command: ['sh', '-c', 'until nc -z $MARIADB_SERVICE_HOST $MARIADB_SERVICE_PORT; do echo waiting for database $MARIADB_SERVICE_HOST; sleep 2; done']
  backoffLimit: 100