apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naad-logs
  labels:
    app.kubernetes.io/name: naad-logs
    app.kubernetes.io/component: socket
    app.kubernetes.io/part-of: naad-connector
    app.kubernetes.io/instance: naad
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
