apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- build-pipeline.yaml
- build-pipelinerun.yaml
- start-build.yaml

labels:
- includeSelectors: true
  pairs:
    app: naad
    env: tools
    app.kubernetes.io/name: naad
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/part-of: naad-connector