apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../openshift
- socket-server

configMapGenerator:
- behavior: merge
  name: naad1-config
  literals:
    - NAAD_URL=e2e-socket-server
- behavior: merge
  name: naad2-config
  literals:
    - NAAD_URL=mariadb

# Overrides the namespace
namespace: default

labels:
- includeSelectors: true
  pairs:
    app: naad-app
    env: default