apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../local
- socket-server

configMapGenerator:
- behavior: merge
  name: naad-config
  literals:
    - NAAD_URL=e2e-socket-server

images:
- name: bcgovgdx/naad-app
  newTag: latest

# Overrides the namespace
namespace: default

labels:
- includeSelectors: true
  pairs:
    app: naad-app
    env: default