name: Build Image on Push.
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch:
defaults:
    run:
        working-directory: ./
jobs:
    deploy_naad_app:
        if: github.repository_owner == 'bcgov'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install OpenShift CLI
              run: |
                curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
                tar -xvf oc.tar.gz
                chmod +x oc
                sudo mv oc /usr/local/bin/
                oc version

            - name: Login to OpenShift and open the correct namespace
              uses: redhat-developer/openshift-actions@v2.0
              with:
                version: 'latest'
                openshift_server_url: ${{ secrets.OpenShiftServerURL }}
                parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
                cmd: |
                    oc project ${{ secrets.OpenShiftNamespace }}

            - name: Create PipelineRun
              run: |
                oc create -f deployments/kustomize/pipelines/build-pipelinerun.yaml
