name: CI

on:
  pull_request:
  push:
      branches:
          - main

permissions:
  contents: read

jobs:
  tests:
      name: Tests

      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            coverage: xdebug

        - name: Validate composer.json and composer.lock
          run: composer validate
            
        - name: Install dependencies with composer
          run: composer update --no-ansi --no-interaction --no-progress

        - name: Linting (PHPCS)
          run: composer run phpcs
          
        - name: Run tests with phpunit/phpunit
          run: vendor/bin/phpunit --coverage-clover=coverage.xml
          
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v4
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}