name: PHP Lint and Unit Tests
on:
  pull_request:
    paths:
      - "**.php"
  workflow_dispatch:
jobs:
  run-php:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Linting (PHPCS)
        run: composer run phpcs
      
      - name: Test coverage (PHPUnit)
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
