name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-tests:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #v2.37.2
        with:
          php-version: '8.5'
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Linting (PHPCS)
        run: composer run phpcs

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4 #v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      ## TODO: Automatically deploy to dev environment

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      security-events: write
    steps:
      - name: Build
        uses: bcgov/action-builder-ghcr@fd17bc1cbb16a60514e0df3966d42dff9fc232bc #v4.0.0
        with:
          package: naad-connector
          build_context: .
          tags: |
            dev
            ${{ github.event.number }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 #v0.36.0
        with:
          image-ref: 'ghcr.io/bcgov/naad-connector/naad-connector:${{ github.event.number }}'
          output: 'trivy-results.sarif'
          trivy-config: '.github/trivy.yml'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'