kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-db-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  ingress:
    - ports:
        - protocol: TCP
          port: 3306
  policyTypes:
    - Ingress
